version: '3'

services:
  postgres:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: postgres
    environment:
      POSTGRES_DB: monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/
